// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Budget_Tracker_Persistence.Models
{
    public partial class Account
    {
        public Account()
        {
            Transaction = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        public int AccountNumber { get; set; }
        public decimal RunningBalance { get; set; }
        public int? ProductId { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}