// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Budget_Tracker_Persistence.Models
{
    public partial class Bank
    {
        public Bank()
        {
            Product = new HashSet<Product>();
            Transaction = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}