// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Budget_Tracker_Persistence.Models
{
    public partial class Transaction
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public decimal? BankCharge { get; set; }
        public int? TransactionTypeId { get; set; }
        public int? AccountId { get; set; }
        public int? BankId { get; set; }
        public int? ProductId { get; set; }

        public virtual Account Account { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Product Product { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}